### ISSUE TITLE
Class usage in final module

### ISSUE THREAD

**Issue by diberry** [pkellner/pluralsight-course-using-react-hooks#3]
In the final module, dealing with authentication, the _app.js uses a class instead of a function. You don't discuss why you use a class here where as other places in the course you are definitely not intersted in used classes. 

What is the difference?

**Comment by pkellner** [comment]
_app.js is a very special file that is prescribed by nextjs. I tried not to get too carried away with server-side rendering in this course, though, it's integral to auth working. The nextjs team has not created a functional version of _app.js, though it is clearly possible they could and maybe will.

For auth to work, there needs to be a way to pass the data from the request object coming in, into the react components.  _app.js combined with getInitalProps is how it does that.

Make sense? (you are right that I did stay away from classes and plan on doing that more in the future also)
