### ISSUE TITLE
Not bug, more of an optimisation

### ISSUE THREAD

**Issue by AdeOpe** [pkellner/pluralsight-course-using-react-hooks#9]
Hi Peter, 
Thanks for the brilliant course on pluralsight.
I gave it an excellent rating.

This is not a bug, just more of an optimisation.

I think the removal of the "return item" on [line 6 in speakersReducer.js](https://github.com/pkellner/pluralsight-course-using-react-hooks/blob/d8bf003c9496761cf60f420dce69ddb5ae4ab307/03-More-React-Hooks-useContext-useReducer-useCallback-useMemo/clip08-useReducer-and-Multiple-Actions/src/speakersReducer.js#L6)  would remove one extra line of code and not affect the execution of the code, since there's a subsequent  "return item" two lines down.

it's a little pedantic on my part, so feel free to ignore and close this ticket if you will.
(ps i did try to do a pull request but i don't have access - which is fair enough)

Thanks again for the course

**Comment by pkellner** [comment]
Thanks @AdeOpe , excellent point and you are being very nice :).  I don't see any reason why I kept that code in there. Feel free to create a pull request and I'll take it.

**Comment by pkellner** [comment]
Sorry @AdeOpe . I just read the part about you not having permission to create a pull request. I'm not sure why that would happen. I think anyone can create a pull request on any public repo. You have to clone the repo first, then make the change in your clone, then create the pull request.

**Comment by AdeOpe** [comment]
ah, you are absolutely right! it was my ssh keys.
I have regenerated the keys and will create a PR shortly.

**Comment by AdeOpe** [comment]
Hi @pkellner 
The code change ready to go.
I also updated the other speakersReducer.js  files also.

![image](https://user-images.githubusercontent.com/5416277/82759269-35446300-9de4-11ea-942b-c606b757b149.png)

However it seems that I don't have write access.

**Comment by AdeOpe** [comment]
Hi @pkellner ,
I created PR using a fork of your code, making my changes in the fork then opening a PR

https://github.com/pkellner/pluralsight-course-using-react-hooks/pull/10

Cheers
